name: Cargo Test

on:
  push:
    branches:
      - main
  release:
    types: [published]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  run-tests:
    runs-on: pop-os
    steps:
      - name: RUSTUP
        run: |
          rustup target add x86_64-unknown-linux-musl
      - name: Checkout repository (via HTTPS API)
        uses: actions/checkout@v4
        with:
          github-server-url: "https://git.fetchbroadcast.tools"
      - name: Cargo Run --Release
        run: cargo build --release --target x86_64-unknown-linux-musl
      - name: Upload Build
        uses: actions/upload-artifact@v3
        with:
          name: build-linux
          path: |
            target/release/*