name: Cargo Test

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  make-linux-binary:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/catthehacker/ubuntu:rust-22.04
    steps:
      - name: Checkout repository (via HTTPS API)
        uses: actions/checkout@v4
      - name: cargo test
        run: cargo test