use assert_cmd::prelude::*;
use assert_fs::TempDir;
use predicates::prelude::*;
mod common;

#[test]
fn generate_when_config_present() {
    let temp = TempDir::new().unwrap();
    // Use legacy alf.conf to exercise migration
    common::copy_fixture_to(&temp, "generate/alf.conf", "alf.conf");

    let mut c = common::cmd();
    c.current_dir(temp.path()).arg("generate");
    c.assert()
        .success()
        .stdout(predicate::str::contains("# This file was automatically generated by ralf"))
        .stdout(predicate::str::contains("unalias g"))
        .stdout(predicate::str::contains("case \"$1\" in"))
        .stdout(predicate::str::contains("# Completions"))
        .stdout(predicate::str::contains("if [ -n \"$ZSH_VERSION\" ]"))
        .stdout(predicate::str::contains("complete -W \"s c l p\" g"))
        .stdout(predicate::str::contains("complete -W \"again\" say"))
        .stdout(predicate::str::contains("complete -W \"ls deploy upd\" dc"));
}

#[test]
fn generate_when_config_missing() {
    let temp = TempDir::new().unwrap();
    let mut c = common::cmd();
    c.current_dir(temp.path()).arg("generate");
    c.assert()
        .failure()
        .stdout(predicate::str::starts_with("ERROR: Cannot find config file"));
}

#[test]
fn generate_no_subcommands_has_no_completions() {
    let temp = TempDir::new().unwrap();
    common::copy_fixture_to(&temp, "no-subcommands/alf.conf", "alf.conf");

    let out = common::cmd()
        .current_dir(temp.path())
        .arg("generate")
        .output()
        .unwrap();
    let s = String::from_utf8_lossy(&out.stdout);
    assert!(s.contains("unalias greet"));
    assert!(!s.contains("# Completions"));
}
